### ISSUE TITLE
Feature Request: Add tqdm for verbose processing

### ISSUE THREAD

**Issue by ichitaka** [cosanlab/py-feat#104]
Currently, the verbose flag for Detector.detect_image is not used at all. When processing a folder with lots of frames, one can expect that the processing will take a long time. A nice extension would be to add the tqdm dependency and show a progress bar for long lists of images when the verbose flag is set. A similar feature could be added for the video processing.

**Comment by ljchang** [comment]
This is now implemented in the soon to be released new version that uses pytorch dataloaders (https://github.com/cosanlab/py-feat/pull/133).

**Comment by ejolly** [comment]
Added in 0.5.0
