### ISSUE TITLE
Enhancement: Use `logging` module in place of `print` statements

### ISSUE THREAD

**Issue by chinvib66** [cosanlab/py-feat#110]
Currently, py-feat uses `print` statements everywhere to communicate with stdout. This may not be the best practice for debugging purposes or in production environments. 

It would be really helpful if the project uses configurable logging libraries, like python's `logging`, for communication with stdout.

A StackOverflow link on why to use logging: https://stackoverflow.com/questions/6918493/in-python-why-use-logging-instead-of-print

**Comment by TiankangXie** [comment]
@chinvib66 That is an excellent suggestion! We will release an update addressing on this issue!
