### ISSUE TITLE
"Unable to load data  pyfeat_aus_to_landmarks.h5 : can't set attribute" and "AttributeError: 'PLSRegression' object has no attribute '_x_mean'"

### ISSUE THREAD

**Issue by dexterdev** [cosanlab/py-feat#112]
```
from feat.plotting import plot_face

plot_face(au = np.zeros(20))
```

gives error:

```
Unable to load data  pyfeat_aus_to_landmarks.h5 : can't set attribute
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-223-c9f91a58ea32> in <module>
      1 from feat.plotting import plot_face
      2 
----> 3 plot_face(au = np.zeros(20))

~/.conda/envs/new/lib/python3.8/site-packages/feat/plotting.py in plot_face(model, au, vectorfield, muscles, ax, feature_range, color, linewidth, linestyle, gaze, *args, **kwargs)
    907         )
    908 
--> 909     landmarks = predict(au, model, feature_range = feature_range)
    910     currx, curry = [landmarks[x, :] for x in range(2)]
    911 

~/.conda/envs/new/lib/python3.8/site-packages/feat/plotting.py in predict(au, model, feature_range)
    980         au = minmax_scale(au, feature_range=feature_range, axis=1)
    981 
--> 982     landmarks = np.reshape(model.predict(au), (2, 68))
    983     # landmarks[1, :] = -1 * landmarks[1, :]  # this might not generalize to other models
    984     return landmarks

~/.conda/envs/new/lib/python3.8/site-packages/sklearn/cross_decomposition/_pls.py in predict(self, X, copy)
    452         X = self._validate_data(X, copy=copy, dtype=FLOAT_DTYPES, reset=False)
    453         # Normalize
--> 454         X -= self._x_mean
    455         X /= self._x_std
    456         Ypred = np.dot(X, self.coef_)

AttributeError: 'PLSRegression' object has no attribute '_x_mean'
```

Can someone look into it?

**Comment by TiankangXie** [comment]
@jcheong0428 Is it possible for you to look over this issue a little bit?

**Comment by Szenteczki** [comment]
Hi @dexterdev @TiankangXie @jcheong0428 

This issue seems to stem from line 221 in utils.py - I think your version check has been broken after scikit-learn updated from X.2X.XX to 1.X.X version numbering.

Some of the other recent issues such as #114 and #115 may also be due to updates in dependencies being auto-installed by pip.

In the meantime, a workaround for the issue with plot_face is to roll back the version of sklearn after installing Py-Feat

`pip install --force-reinstall scikit-learn==0.24.2`

**Comment by ejolly** [comment]
@Szenteczki @dexterdev This is now fixed in the master branch on github. We plan to have a new release on PyPI soon, but for now you can install directly from github using: `pip install git+https://github.com/cosanlab/py-feat.git`

**Comment by liuqing-psy** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nilearn 0.10.2 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
py-feat 0.6.1 requires scikit-learn>=1.2, but you have scikit-learn 0.24.2 which is incompatible.
We tried the above methods, but still got an error
