### ISSUE TITLE
pyfeat_aus_to_landmarks.h5 does not exist in new version (0.4.0) 

### ISSUE THREAD

**Issue by Ben-FCC** [cosanlab/py-feat#126]
![截圖 2022-06-12 下午10 07 19](https://user-images.githubusercontent.com/65886339/173237150-ac6dd458-7278-4e07-95db-b5fc50003819.png)

**Comment by clviegas** [comment]
Hi @Ben-FCC , here is how I fixed that problem:
1. Look up the URL of the file which is missing in https://github.com/cosanlab/py-feat/tree/main/feat/resources/model_list.json
2. Go to the folder where it should be 
3. Use wget to download the missing file

You will need pyfeat_aus_to_landmarks.h5 and pyfeat_aus_to_landmarks.joblib.

I hope this helps!

**Comment by Ben-FCC** [comment]
Hi @clviegas, 
Your suggestion is really helpful!

Thanks a lot!
