### ISSUE TITLE
AU plotting with JAANET

### ISSUE THREAD

**Issue by YuhaoHuangMD** [cosanlab/py-feat#127]
Hi there,

Just wanted to point out a bug while using AU plotting when using JAANET as the AU detector. The AUs are not correctly plotted onto the face, and adding Muscles = True throws an exception:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/76924016/173469663-617b8e8a-4221-461d-9972-b6f2e3b86b77.png">

**Comment by ejolly** [comment]
Since 0.5.0 we no longer support JAANET
