### ISSUE TITLE
Batch_size issue in latest update

### ISSUE THREAD

**Issue by ritika24-s** [cosanlab/py-feat#130]
in detect_video
    and (concat_frame.shape[0] % batch_size == 0)
TypeError: unsupported operand type(s) for %: 'int' and 'str'

Hi, everytime I try to run Py-feat detector (au_model='svm', emotion_model='svm') and detect_Video with skip_frames=30, I am getting this issue.

It will be great if you can change the position of batch_size argument to end, so that it doesnt affect the code written for older versions

**Comment by viniciusparede** [comment]
i have the same problem

**Comment by ljchang** [comment]
We are completely refactoring how batching is done, which should address this issue.  It's done, but not working with all detectors yet https://github.com/cosanlab/py-feat/pull/133.

**Comment by ejolly** [comment]
Fixed in 0.5.0
