### ISSUE TITLE
Different pretrained AU models expect different inputs

### ISSUE THREAD

**Issue by maltelueken** [cosanlab/py-feat#131]
It seems that the pretrained AU models expect different input sizes for the landmarks argument. A detector with `au_model='JAANET'` allows for a landmarks argument with 3 dimensions (e.g., landmarks for multiple images/frames) when calling `detect_aus()`. Detectors with `au_model='svm'` or `logistic` only allow for landmark arguments with 2 dimensions (e.g., a single frame). This behavior makes it quite difficult to simply swap the models in a pipeline.

**Comment by ejolly** [comment]
Fixed in 0.5.0
