### ISSUE TITLE
Missing facepose property in version 0.3.7

### ISSUE THREAD

**Issue by harlanhong** [cosanlab/py-feat#132]
Hi, 

When I install version 0.3.7, and run:
`out = detector.detect_image(img_path)
  gt_aus = out.facepose().values`
an error was called:
![image](https://user-images.githubusercontent.com/19970321/177719260-552c8367-321c-4fcc-a8e7-d9103f9b1abd.png)

But this interface was available half a year ago.

**Comment by Carlyx** [comment]
Hi~ @harlanhong 
Did you solve this problem?

**Comment by ejolly** [comment]
Fixed in 0.5.0
