### ISSUE TITLE
How to use au_model="rf" and emotion_model = "rf" in version 0.4

### ISSUE THREAD

**Issue by ritika24-s** [cosanlab/py-feat#134]
Hi,

I wish to use au_model="rf" since RF model gives the intensity as random continuous variable unlike SVM which just gives the possiblity of detecting aus for my analysis.

It was possible in version 0.3.7 but is not in latest version. What's the alternative for this? Also, my requirement is to use HOG based models only for au and emotions. So I can only use either RF or SVM. Is there any alternative for it?

**Comment by ljchang** [comment]
hi @ritika24-s , We discovered an issue with the output of the RF model, which we haven't had time to fully debug or retrain yet. We disabled it in version 4.0, but plan to revisit adding it in the next version. It might not be too hard to convert the SVM output into probabilities using platt scaling, but I'm not sure if we are retaining enough information in the model to do that without retraining it. 

We are currently in the process of doing another major refactor to the code and the AU detector module is next up in the queue, so we should have more info about this soon.

**Comment by ritika24-s** [comment]
Hi Luke,

Thanks for replying. I am using PyFeat for my thesis.

In your expert opinion, do you think using the rf model to get AU intensities is still okay? Because my submission is in August and I tried working with SVM but it really doesn't solve my problem at all.

I would love to know your opinion on it.

**Comment by timboh619** [comment]
I have long used the rf model from the older version and have recently noticed that the AU intensities are significantly different than the newer AU models in version 0.4. 

I am also curious to hear if anyone has found the old rf model to be inaccurate.

**Comment by ritika24-s** [comment]
Hi Luke,

Thanks for replying. I am using PyFeat for my thesis.

In your expert opinion, do you think using the rf model to get AU
intensities is still okay? Because my submission is in August and I tried
working with SVM but it really doesn't solve my problem at all.

I would love to know your opinion on it.

**Comment by akiratsuraii** [comment]
Hello Ritika,
I'm attempting to use PyFeat for my thesis to obtain the AU intensities also, but it seems that PyFeat is not the greatest option at this time. 
Could you share to me what you did afterall?Do you still with PyFeat?
I'm hoping you'll share with me. Many thanks :D

**Comment by ejolly** [comment]
Hi @ritika24-s @akiratsuraii please check out our latest release (0.5.0) in which we've added/retrained our AU. Our new default is now `xgb` which gives continuous valued predictions between 0-1. 

Hey @med-tim as mentioned by @ljchang our `rf` model was not performing properly and so we've now removed it our latest release and no longer recommend its use.
