### ISSUE TITLE
Error in detect_image()

### ISSUE THREAD

**Issue by TalBarami** [cosanlab/py-feat#137]
Hey,
When I attempt to use the detector on a single image with a single face, I receive an IndexError coming from `detector.py`:
`facepose_df = pd.DataFrame(
                        [poses[i][j].flatten(order="F")],
                        columns=self["facepose_model_columns"],
                        index=[counter + j],
                    )`

For some reason, the first session in `detected_faces` contains 6 faces, yet `poses` contains only 1

**Comment by ejolly** [comment]
Fixed in 0.5.0
