### ISSUE TITLE
Support for FaceReader data files

### ISSUE THREAD

**Issue by nomader** [cosanlab/py-feat#146]
It would be great to also have support for [FaceReader](https://www.noldus.com/facereader), which is the most cited automated face/AU analysis tool of all. (I see that currently only OpenFace, FACET and Affective are supported as AU detections data files.)

FaceReader's output logs can be .csv (tab separated) or .xlsx (excel) files. It can contain basic emotions, several AUs, head and gaze orientations information, heart rate information, etc. Here's an [example](https://github.com/cosanlab/py-feat/files/9990728/FaceReader.example.log.txt).

**Comment by ejolly** [comment]
Unfortunately in our latest release we've dropped support for FACET and Affectiva as the maintenance burden with additional features was becoming too great for our small team. So I don't think we'll have the capacity to add this...we're always happy to take pull-requests though!
