### ISSUE TITLE
How to handle Errors in each module?

### ISSUE THREAD

**Issue by TiankangXie** [cosanlab/py-feat#147]
In our main function detect_image, we have not designed how to **handle errors**  for each module. Errors in theory can happen in one or all modules among the detect face, detect landmark, detect au or detect emotion. 

We could just fill up NANs for the failed module. Or we want to raise more informative errors? What do you guys think?  @ljchang @ejolly

**Comment by ejolly** [comment]
Fixed in 0.5.0
