### ISSUE TITLE
Anything wrong with the SVM model of au detector in v0.5.0?

### ISSUE THREAD

**Issue by alfajya** [cosanlab/py-feat#152]
I have tried the new released v0.5.0 py-feat to detect facial expressions from the test image ("single_face.jpg"),  finding that there may be something wrong with the au_models. By applying "svm" as the au_model for Detector, I got the wrong output aus. 
![image](https://user-images.githubusercontent.com/120166424/207829525-bdb5ace3-1228-4bfb-9291-a548d6d1536e.png)
And the plotted pictures were like these. 
![myplot](https://user-images.githubusercontent.com/120166424/207830128-1bc062ea-e2a5-4a73-a998-86199d7a25af.png)
![myplot2](https://user-images.githubusercontent.com/120166424/207830132-5c412955-dba8-46aa-86d2-86c49166975d.png)

**Comment by ejolly** [comment]
Hi @alfajya the SVM model returns binary predictions for AU detections (i.e. either 0 or 1), so this is intended behavior. What were you expecting?

**Comment by ejolly** [comment]
I've updated our docs to make this clear: https://py-feat.org/pages/models.html 

Feel free to reopen if this isn't the issue

**Comment by alfajya** [comment]
> Feel free to reopen if this isn't the issue

Thanks a lot.
