### ISSUE TITLE
Issue with the code for extracting hog in AU detection.

### ISSUE THREAD

**Issue by chinaheyu** [cosanlab/py-feat#163]
In line 577 of the file `feat/detector.py`:

```python
hog_features.append(
    hog(
        transforms.ToPILImage()(convex_hull[0]),
        orientations=8,
        pixels_per_cell=(8, 8),
        cells_per_block=(2, 2),
        visualize=False,
        channel_axis=-1,
    ).reshape(1, -1)
)
```

The images in `convex_hull` are represented in the range 0-255, but the `transforms.ToPILImage` function only accepts inputs from 0-1 of type `torch.Tensor`.

If you debug the images in the `transforms.ToPILImage()(convex_hull[0])`, you will see this confusing result:

![tmpmd3p1jlr](https://user-images.githubusercontent.com/59406481/226403308-5cfd248d-e89c-431d-8ce9-60c75a6e0ef8.PNG)

Line 577 could easily be modified to fix this bug, but I don't know what effect this modification would have on the AU detection. But one thing is for sure that there must be problems with the original code. In my experiments, even the same image with different size will get completely different AU results.

Here is my modified code.

```python
hog_features.append(
    hog(
        transforms.ToPILImage()(convex_hull[0] / 255.0),
        orientations=8,
        pixels_per_cell=(8, 8),
        cells_per_block=(2, 2),
        visualize=False,
        channel_axis=-1,
    ).reshape(1, -1)
)
```

I'm not sure how many impacts this will have. I think the worst outcome is to retrain the classifier.

**Comment by ljchang** [comment]
Great catch @chinaheyu !  Not sure how we missed this. The hog features are definitely not correct without rescaling by 255.  

![Screenshot 2023-03-30 at 8 54 21 PM](https://user-images.githubusercontent.com/2993338/228996530-505b7600-4364-4e55-ba5f-c8fd1ad08f85.png)


We will look into this further and will likely need to retrain all of the models that use this. 

We will keep you posted. Thanks so much for digging into this!

**Comment by ejolly** [comment]
Thank you again! We have now fixed this and retrained the affecte models in 0.6.0
