### ISSUE TITLE
The Frame sequence number repeated in the processing result of Detector.detect_video

### ISSUE THREAD

**Issue by xingrenyuuu** [cosanlab/py-feat#165]
Hello,
When I use Detector.detect_video to process the video file (with skip_frames set), I save it to csv. However, I found duplicate frame numbers in the csv file frame, and their other values are not the same (indicating that they are not the same frame). How did this happen?

I tried to look at the video_dataset code and found no bugs. This may be related to my identity as a junior programmer, and I hope to get answers from professionals.

Thank you very much.
![error_frame](https://github.com/cosanlab/py-feat/assets/92592146/f53c43a5-16b2-47f6-ab7c-7031803d774c)

**Comment by Ben-FCC** [comment]
Hi @xingrenyuuu,

I'm also the user. 
I guess it means that the model detects two different faces in the same frame.

**Comment by xingrenyuuu** [comment]
> Hi @xingrenyuuu,
> 
> I'm also the user. I guess it means that the model detects two different faces in the same frame.

I looked at the original video and it was just a face from beginning to end. Another point is that I looked at a lot of csv files, and the repeated frames appeared irregularly. Have you ever had such a situation?

**Comment by Ben-FCC** [comment]
> > Hi @xingrenyuuu,
> > I'm also the user. I guess it means that the model detects two different faces in the same frame.
> 
> I looked at the original video and it was just a face from beginning to end. Another point is that I looked at a lot of csv files, and the repeated frames appeared irregularly. Have you ever had such a situation?

Hi @xingrenyuuu ,

I have had such a situation too, and I think it's just the detection error of the model. 
My solution is choosing the output with a higher `FaceScore` to represent that frame.

Hope this is helpful for you.

**Comment by ljchang** [comment]
Thanks for sharing this bug. We haven't noticed this yet in our tests. Can you share more details about your call to the detector?  Are you using parallel processing etc?   Any details to help us replicate this can help speed up the debugging.

**Comment by xingrenyuuu** [comment]
> Thanks for sharing this bug. We haven't noticed this yet in our tests. Can you share more details about your call to the detector? Are you using parallel processing etc? Any details to help us replicate this can help speed up the debugging.

> @ljchang Thank you for noticing this bug! I just want to try to use py-feat to simply analyze dozens of face videos (about 2 minutes, all single person interviews). I wrote a for loop to handle them.
`import os
from feat import Detector

path = r"E:\talk_face_videos\Dep"
path_videos = os.listdir(path)
print(path_videos)

detector = Detector(face_model="retinaface",
    landmark_model="mobilefacenet",
    au_model='xgb',
    emotion_model="resmasknet",
    facepose_model="img2pose",
)

for i in path_videos:
    path_video = os.path.join(path, i)
    num = os.path.splitext(i)[0]
    video_prediction = detector.detect_video(path_video, skip_frames=60)
    video_prediction.to_csv(fr"E:\talk_face_videos\pyfeat_csvs/{num}.csv", index=False)
#
    detector = Detector(face_model="retinaface",
                        landmark_model="mobilefacenet",
                        au_model='xgb',
                        emotion_model="resmasknet",
                        facepose_model="img2pose",
                        )`
I checked all the csv files, some of the "frame" column values are exactly correct, and some of the csvs frames are still irregularly repeated frames. I guess it has to do with the FPS value of the video and the related calculation of skip_frames (the convention of rounding).

**Comment by xingrenyuuu** [comment]
> Thank you for noticing this bug! @ljchang 
 I just want to try to use py-feat to simply analyze dozens of face videos (about 2 minutes, all single person interviews). I wrote a for loop to handle them.
```
import os
from feat import Detector
path = r"E:\talk_face_videos\Dep"
path_videos = os.listdir(path)
print(path_videos)
detector = Detector(face_model="retinaface",
landmark_model="mobilefacenet",
au_model='xgb',
emotion_model="resmasknet",
facepose_model="img2pose",
)
for i in path_videos:
path_video = os.path.join(path, i)
num = os.path.splitext(i)[0]
video_prediction = detector.detect_video(path_video, skip_frames=60)
video_prediction.to_csv(fr"E:\talk_face_videos\pyfeat_csvs/{num}.csv", index=False)
detector = Detector(face_model="retinaface",
                    landmark_model="mobilefacenet",
                    au_model='xgb',
                    emotion_model="resmasknet",
                    facepose_model="img2pose",
                    )
```
I checked all the csv files, some of the "frame" column values are exactly correct, and some of the csvs frames are still irregularly repeated frames. I guess it has to do with the FPS value of the video and the related calculation of skip_frames (the convention of rounding).

**Comment by xingrenyuuu** [comment]
Thank you for noticing this bug! @ljchang
I just want to try to use py-feat to simply analyze dozens of face videos (about 2 minutes, all single person interviews). I wrote a for loop to handle them.
```
import os
from feat import Detector

path = r"E:\talk_face_videos\Dep"
path_videos = os.listdir(path)
print(path_videos)

for i in path_videos:
    path_video = os.path.join(path, i)
    print(path_video)
    num = os.path.splitext(i)[0]
    print(num)
    video_prediction = detector.detect_video(path_video, skip_frames=10)
    video_prediction.to_csv(fr"E:\talk_face_videos\pyfeat_csvs/{num}.csv", index=False)
    detector = Detector(face_model="retinaface",
                        landmark_model="mobilefacenet",
                        au_model='xgb',
                        emotion_model="resmasknet",
                        facepose_model="img2pose",
                        )
```
I checked all the csv files, some of the "frame" column values are exactly correct, and some of the csvs frames are still irregularly repeated frames. I guess it has to do with the FPS value of the video and the related calculation of skip_frames (the convention of rounding)

**Comment by ejolly** [comment]
We're hoping our new 0.6.0 release should avoid this issue due to re-worked video loading

**Comment by xingrenyuuu** [comment]
Thank you for your reply.I just used the new 0.6.0 release of pyfeat, but I still had the same problem with repeated frames.
You and your team could take note of the FaceScore column values. In my results, the duplicate frames (except for the first one) are in rows with a low FaceScore.

&nbsp;








张晟铭



南方科技大学/研究生/研究生2021级



广东省深圳市南山区学苑大道1088号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Eshin&nbsp;Jolly"; 
Date: 2023年7月11日(星期二) 上午6:54
To: "cosanlab/py-feat"; 
Cc: ***@***.***>; "Mention"; 
Subject: Re: [cosanlab/py-feat] The Frame sequence number repeated in the processing result of Detector.detect_video (Issue #165)

&nbsp;


 
We're hoping our new 0.6.0 release should avoid this issue due to re-worked video loading

**Comment by ejolly** [comment]
@xingrenyuuu Can you share the output? It didn't appear in your last message. Also can you try playing with the `skip_frames` (setting to 1 for example) to see if that resolves the issue? It could still be a rounding issue

**Comment by xingrenyuuu** [comment]
> @xingrenyuuu Can you share the output? It didn't appear in your last message. Also can you try playing with the `skip_frames` (setting to 1 for example) to see if that resolves the issue? It could still be a rounding issue
@ejolly Excuse me. The output file cannot be shared for the time being. I'll try to set up skip_frame later. I just came across this little problem in my research and wanted to share this finding. I'm not sure anyone else has the same problem.

**Comment by xingrenyuuu** [comment]
@ejolly Sorry, the output file cannot be shared for the time being. After that I will try to set skip_frame to 1, but I have tried to set it to 10, 30. I just came across this little problem in my research and wanted to share this finding. I'm not sure anyone else has the same problem.

**Comment by ejolly** [comment]
@xingrenyuuu  No worries. If it is a rounding error, I imagine setting skip_frames to 1, or some number divisible by your video's framerate, e.g. 24, 30, 60, might solive it. I'm going to close for now but feel free to reopen if this seems like a major issue you keep encountering, as I'm sure you won't be the only one.
