### ISSUE TITLE
404 error when loading detector model using pyfeat

### ISSUE THREAD

**Issue by j55blanchet** [cosanlab/py-feat#171]
I have a fresh install of Python3.9 on a Windows 11 machine. I've installed py-feat using pip per the instructions. 

It's giving me an HTTP 404 error when attempting to create the `Detector` object. Here's the script:

```
from pathlib import Path
from feat import Detector

def detect_emotions(video_path: Path, outdir: Path, overwrite: bool):
    
    out_csv_path = outdir / (video_path.with_suffix('.csv').name)

    if out_csv_path.exists() and not overwrite:
        print(f'\tOutput file {out_csv_path} already exists, skipping')
        return
    
    face_model = "retinaface"
    landmark_model = "mobilenet"
    au_model = "xgb"
    emotion_model = "resmasknet"

    expression_detector = Detector(
        face_model = face_model, 
        landmark_model = landmark_model, 
        au_model = au_model, 
        emotion_model = emotion_model
    )

    video_prediction = expression_detector.predict_video(str(video_path))
    out_csv_path.parent.mkdir(parents=True, exist_ok=True)
    video_prediction.to_csv(str(out_csv_path), index=True)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()

    parser.add_argument('--srcfile', type=Path, default=Path('data/vid.mp4'))
    parser.add_argument('--outdir', type=Path, default=Path('output'))
    parser.add_argument('--overwrite', action='store_true', default=False)
    args = parser.parse_args()

    detect_emotions(args.srcfile, args.outdir, overwrite=args.overwrite)
    
```
Here's the error it's giving me:
```
Exception has occurred: HTTPError
HTTP Error 404: Not Found
  File "D:\dev\temp\pyfeat\example.py", line 17, in detect_emotions
    expression_detector = Detector(
  File "D:\dev\temp\pyfeat\example.py", line 38, in <module>
    detect_emotions(args.srcfile, args.outdir, overwrite=args.overwrite)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

In the terminal, I see two progress bars completed as output:
```
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1786259/1786259 [00:00<00:00, 13630227.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 45339002/45339002 [00:03<00:00, 13820401.33it/s]
```

**This makes me think that perhaps the model is failing to find the model files for one of the modules.**

If it helps, here is the output of `pip freeze`:
```
av==10.0.0
blosc2==2.0.0
celluloid==0.2.0
certifi==2023.5.7
charset-normalizer==3.1.0
colorama==0.4.6
contourpy==1.1.0
cycler==0.11.0
Cython==0.29.35
deepdish==0.3.7
easing-functions==1.0.4
filelock==3.12.2
fonttools==4.40.0
h5py==3.9.0
idna==3.4
imageio==2.31.1
importlib-resources==5.12.0
Jinja2==3.1.2
joblib==1.3.1
kiwisolver==1.4.4
kornia==0.6.12
lazy_loader==0.2
lxml==4.9.2
MarkupSafe==2.1.3
matplotlib==3.7.1
mpmath==1.3.0
msgpack==1.0.5
networkx==3.1
nibabel==5.1.0
nilearn==0.10.1
nltools==0.4.7
numexpr==2.8.4
numpy==1.25.0
packaging==23.1
pandas==2.0.3
Pillow==9.5.0
py-cpuinfo==9.0.0
py-feat==0.5.1
pynv==0.2
pyparsing==3.1.0
python-dateutil==2.8.2
pytz==2023.3
PyWavelets==1.4.1
requests==2.31.0
scikit-image==0.21.0
scikit-learn==1.2.2
scipy==1.11.1
seaborn==0.12.2
six==1.16.0
sympy==1.12
tables==3.8.0
threadpoolctl==3.1.0
tifffile==2023.4.12
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.0
typing_extensions==4.7.0
tzdata==2023.3
urllib3==2.0.3
xgboost==1.7.6
zipp==3.15.0
```

**Comment by dramsay9** [comment]
I'm also seeing this when I try to initialize the detector the first time, both locally and on on the provided colab. I'm thinking it might be these cosanlab/py-feat/releases/download/v0.1/Oct30FinalXGB...ubj files that don't seem to be available anymore.  

If you look into the site-packages/feat/resources/model_list.json, you'll see the list of urls it pulls from on cosanlab/releases.   On the github releases page, if you scroll down, you can see the model files, and they were updated a couple days ago and their names have changed (so instead of Oct30 they now are June25).  You can edit the filenames to match.

**Comment by dramsay9** [comment]
..and after playing with this for a while I am struggling to get it to work.  Multiple of the pretrained files have changed and it looks like some of the pickles that used to include both scalar and pca data are now broken into two separate pickles.  I tried downloading both and loading both but XGB is giving me dimension errors when I try to predict on the test video.

Hopefully someone fixes it soon to match the new resource files, seems like a great tool to use!

**Comment by Timozen** [comment]
This seems to be an issue with the links in the `model_list.json` file.
I investigated all broken links and updated the files in my local repo copy.
So to fix the issue, you have to clone the repo and install it locally; the pip install is definitely broken right now 😢 

In the local `model_list.json` replace the `au_detectors` with the following:

```json
    "au_detectors": {
        "svm": {
            "urls": [
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/svm_60_June2023.pkl"
            ]
        },
        "xgb": {
            "urls": [
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU1_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU2_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU4_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU5_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU6_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU7_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU9_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU10_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU11_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU12_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU14_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU15_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU17_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU20_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU23_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU24_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU25_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU26_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU28_XGB.ubj",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/June25_AU43_XGB.ubj"
           ]
        },
        "hog-pca": {
            "urls": [
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/all_data_Upperpca_Jun23.pkl",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/all_data_Lowerpca_Jun23.pkl",
                "https://github.com/cosanlab/py-feat/releases/download/v0.1/all_data_Fullpca_Jun23.pkl"
            ]
        }
    },
```

Then everything should download again, but I cannot make any assumptions about the current state of "correctness" of the downloaded models.

**Comment by Timozen** [comment]
The same has to be done for the SVMClassifier class:

```python

class SVMClassifier:
    def __init__(self) -> None:
        self.scaler_upper = load_classifier_pkl(os.path.join(get_resource_path(), "all_data_Upperscalar_Jun23.pkl"))
        self.pca_model_upper = load_classifier_pkl(os.path.join(get_resource_path(), "all_data_Upperpca_Jun23.pkl"))
        
        self.scaler_lower = load_classifier_pkl(os.path.join(get_resource_path(), "all_data_Lowerscalar_Jun23.pkl"))
        self.pca_model_lower = load_classifier_pkl(os.path.join(get_resource_path(), "all_data_Lowerpca_Jun23.pkl"))
        
        self.scaler_full = load_classifier_pkl(os.path.join(get_resource_path(), "all_data_Fullscalar_Jun23.pkl"))
        self.pca_model_full = load_classifier_pkl(os.path.join(get_resource_path(), "all_data_Fullpca_Jun23.pkl"))
        
        self.classifier = load_classifier(
            os.path.join(get_resource_path(), "svm_60_June2023.pkl")
        )
        
```

**Comment by Timozen** [comment]
I will try to make this fix as a push request as an intermediate workaround, but somehow we should mitigate this behavior with every rolling release.

**Comment by dramsay9** [comment]
I figured out the branch that was being developed that updated the weights; @TiankangXie it looks like your development on the au_fixes branch has broken origin for people that haven't already downloaded the model weight files.

This set of commands works for me to get py-feat working:

```
git clone https://github.com/cosanlab/py-feat
cd py-feat 
git pull origin au_fixes
pip3 install -r requirements-dev.txt
python3 setup.py install
```

I can now successfully run
```
from feat.detector import Detector
from feat.utils.io import get_test_data_path
import os

detector = Detector(verbose=True)

test_data_dir = get_test_data_path()
test_video_path = os.path.join(test_data_dir, "WolfgangLanger_Pexels.mp4")

video_prediction = detector.detect_video(test_video_path, skip_frames=24)
video_prediction.head()
```

**Comment by Timozen** [comment]
This is the case, as I did not have the previous weights downloaded. What would be a workaround for preventing these issues in the future from a coding perspective?

**Comment by TiankangXie** [comment]
@Timozen Thank you for the suggestions. I think we wanted to swap out all the older weights, and I accidentally deleted all the older weights. For compatibility I just uploaded the older weights. I am sorry for the confusion. But I think for future uses we would encourage people to use the updated weights

**Comment by dramsay9** [comment]
Thanks @TiankangXie!  Is there any reason to revert to the old weights/main branch if I'm on your current branch?

**Comment by TiankangXie** [comment]
Hello @dramsay9 , I will encourage you, if you are on my **current branch (au_fixes)**, to **use the most updated weights**, as they are better trained. We will start to merge this branch with the **main branch** soon.

**Comment by Timozen** [comment]
This all sounds like a good plan :) Could the introduction of flags for stable/experimental weights/models be useful? So we would not loose old stable weights used by previous versions, but still are able to experiment newer versions until you declare the stable?

**Comment by TiankangXie** [comment]
Hello @Timozen , I think this can be done too. However, the new weights are strongly encouraged over the older ones. The thing is that we are not really training new models or new weights. We are simply retraining the existing models (model architecture remains the same) using better weight-balancing strategies, in order to further improve the performance and to make the new weights **more compatible with our current detection pipeline**. So rather than "experimental", it's more like a "revision". But we will keep the older weights in the download url too to make older versions compatible.

**Comment by Timozen** [comment]
I fully agree with you! The "revisioned" models should always be used to achieve the best possible performance. However, other users might publish results based on previous model weights. If these weights are not stored by them (because they hardly look at the functioning of the underlying code), reproducibility cannot be guaranteed.
It might also be helpful to track the performance progression of py-feat over time :P
