### ISSUE TITLE
au_model='logistic' not work in py-feat 0.4.0

### ISSUE THREAD

**Issue by qasimjaleel** [cosanlab/py-feat#172]
Hello
 I'm working on a thesis and I've been using py-feat 0.4.0
au_model="logistic"
 the path not found
https://github.com/cosanlab/feat/releases/download/v0.1/Logistic_520.joblib
the error is
HTTPError: HTTP Error 404: Not Found
Can someone help me

**Comment by ejolly** [comment]
Hi @qasimjaleel we not longer support the logistic AU model and are currently finishing up a release retraining all our AU detectors as there was a subtle issue giving problematic predictions. Moving forward we suggest using the xgb or svm au models. We hope to have that released in the next week or so.

**Comment by qasimjaleel** [comment]
Can I get the file  Logistic_520.joblib

**Comment by TiankangXie** [comment]
Yes. I have just uploaded that file, and you can download in our tag page: 
https://github.com/cosanlab/py-feat/releases/tag/v0.1

Please let me know if you @qasimjaleel have any questions!

**Comment by qasimjaleel** [comment]
Thank you so much.


‫في الجمعة، 7 يوليو 2023 في 12:48 ص تمت كتابة ما يلي بواسطة ‪Tiankang Xie‬‏
***@***.***‬‏>:‬
