### ISSUE TITLE
Update or retrain PLS model

### ISSUE THREAD

**Issue by ejolly** [cosanlab/py-feat#185]
@ljchang It looks like sklearn 1.3.1 literally *just* added a new attribute to the `PLS` model called `._predict_1d` which now breaks our plotting since our model was trained on an older version of sklearn where that attribute doesn't exist, so our tests are now failing. Here's their [changelog](https://scikit-learn.org/stable/whats_new/v1.3.html#sklearn-cross-decomposition) and here's their [commit](https://github.com/scikit-learn/scikit-learn/commit/75f3e478d17de3636d37f2be845d0f7b209d388d) 

We can do another version check to add this attribute into `feat.plotting.load_viz_model` [like we are for other attributes](https://github.com/cosanlab/py-feat/blob/main/feat/plotting.py#L1325), but it might be worth just retraining it?

Not sure how we want to handle this kind of backwards compatibility for sklearn models or whether we should pin sklearn version requirements if our models are trained on specific versions.

**Comment by ljchang** [comment]
Is the issue that the model is just incompatible and can't load because it didn't have that attribute when it was trained?  If so, that seems weird, but we should just retrain it.

We may need to do a test and deploy different models depending on the version , which is pretty annoying.
