### ISSUE TITLE
calculation of sampling freq

### ISSUE THREAD

**Issue by jcheong0428** [cosanlab/py-feat#19]
our FACET, OpenFace can calculate sampling frequency by doing a .diff() on the timestamps. 
It would be nice to have that set as the default when sampling_freq is not passed when the class is not initialized.

**Comment by ljchang** [comment]
sounds good to me.  Could be problematic for anything using variable sampling rate.  Might want to guess average sampling rate if so.  Also, could make `sampling_freq='auto'` as the default.  This would try to do what you are suggesting.  Users could still manually specify sampling freq, or it could still be None.  Don't like the idea of None leading to autodetection.

**Comment by Nathaniel-Haines** [comment]
I like the idea of defaulting to 'auto'. That way, it is explicit what is
going on.

**Comment by jcheong0428** [comment]
So saving the timestamps or using the timestamps can make it more explicit what time each datapoint corresponds. It would actually be more useful for data with variable sampling_rate because you would know exactly when each frame was taken not just the order.

**Comment by ljchang** [comment]
I might suggest making timestamps be the index on the object.  that way everything is retained and you can still 'auto' calculate sampling freq.

**Comment by jcheong0428** [comment]
exactly. if we have in the pandas timeformat we could leverage more Series functions too. 
We should test it and see how many things we break

**Comment by ljchang** [comment]
yeah, this could be cool.  I've always been intrigued by this aspect of pandas, but found their time stamp formula to be really annoying.

**Comment by ljchang** [comment]
closing this for now as the toolbox works with single images and videos. However, timestamps will be very trivial to implement now with the new video dataloader class. (https://github.com/cosanlab/py-feat/pull/133).
