### ISSUE TITLE
Using Py-Feat in Python 3.10+

### ISSUE THREAD

**Issue by MarcFraile** [cosanlab/py-feat#191]
We are considering using Py-Feat for research and teaching in my research group at Uppsala University, but a show-stopper right now is the lack of support for newer versions of Python (3.10+).

I have done some preliminary experiments, and the only issue seems to be a dependency on lib2to3 (a module in the standard library that was removed from newer Python versions). As far as I can tell, lib2to3 is only ever imported in feat/emo_detectors/ResMaskNet/resmasknet_test.py, and it's **not used**.

Would it be possible to extend official support to newer Python versions? Of course, it should be properly tested, but I'm quite confident all it would take is to remove one unused line in one file.

**Comment by ljchang** [comment]
Hi @MarcFraile, thanks for your message. Many of us have been using py-feat with newer versions of python. For example, I've been successfully using 3.11 on a M1 mac. Are you receiving a warning or an error with the lib2to3 import?  Can you share more details about your system and python versions?  

We can certainly remove that import line (I'm surprised its even still there!). Feel free to submit a pull request if you want to test this on your own system and speed up the process of getting this addressed.

**Comment by MarcFraile** [comment]
Hi @ljchang , 

You can see the details of my setup at the end of this message. If I start a fresh virtual environment using Python 3.10.13 and only install Py-Feat 0.6.1, I get the following stack trace:

```shell
Traceback (most recent call last):
  File "/home/marcfraile/Documents/scratch/pyfeat-repro/./example.py", line 4, in <module>
    from feat import Detector
  File "/home/marcfraile/Documents/scratch/pyfeat-repro/.venv/lib/python3.10/site-packages/feat/__init__.py", line 11, in <module>
    from .data import Fex
  File "/home/marcfraile/Documents/scratch/pyfeat-repro/.venv/lib/python3.10/site-packages/feat/data.py", line 31, in <module>
    from feat.plotting import plot_face, draw_lineface, draw_facepose, load_viz_model
  File "/home/marcfraile/Documents/scratch/pyfeat-repro/.venv/lib/python3.10/site-packages/feat/plotting.py", line 13, in <module>
    from feat.pretrained import AU_LANDMARK_MAP
  File "/home/marcfraile/Documents/scratch/pyfeat-repro/.venv/lib/python3.10/site-packages/feat/pretrained.py", line 13, in <module>
    from feat.emo_detectors.ResMaskNet.resmasknet_test import ResMaskNet
  File "/home/marcfraile/Documents/scratch/pyfeat-repro/.venv/lib/python3.10/site-packages/feat/emo_detectors/ResMaskNet/resmasknet_test.py", line 4, in <module>
    from lib2to3.pytree import convert
ModuleNotFoundError: No module named 'lib2to3'
```

Here is the full script used to reproduce this bug, for reference:

```python
#!/bin/env -S python3 -u


from feat import Detector


def main():
    detector = Detector()
    print(detector)


if __name__ == "__main__":
    main()
```

As far as I can tell from googling, `lib2to3` is an old module in the standard library that was added in the transition days from Python 2 to Python 3, and is marked for deprecation. It's not officially removed in 3.10, but it seems that it's not compiled by default (case in point, my installation is straight from the Python website and doesn't have the module).

As I said in the original message, the only reference I could find in the Py-Feat code is line 4 in `feat/emo_detectors/ResMaskNet/resmasknet_test.py`:

```python
from lib2to3.pytree import convert
```

This import is not used, so I attempted faking the `lib2to3` module and it seems to work. In the end, I solved the problem by pushing a dummy library to PyPi https://pypi.org/project/mff-lib2to3-fake/

**OS:** Ubuntu 20.04.6 LTS
**Python version:** 3.10.13
**Package manager:** Poetry 1.2.1

**Comment by Azleur** [comment]
I also found an unrelated issue due to version pinning (I had to downgrade scikit-learn to 1.2 from 1.3 in order to avoid an error in the unpickling process when Detector() loads the models, but the Py-Feat requirements file states scikit-learn>=1.2).

**Comment by GeorgeEfstathiadis** [comment]
@ljchang if Py-Feat is supported in Python 3.11, is it possible to update `setup.py` and the pypi metadata to reflect that?
