### ISSUE TITLE
Specifying the temporal profile of AU activation

### ISSUE THREAD

**Issue by hcuve** [cosanlab/py-feat#197]
Firstly, thanks for the great effort in putting together Py-Feat. 

I have a query regarding the AU to landmark visualisation analysis. My current project involves analyzing facial action patterns over time, and I am particularly interested in creating animations that follow exactly the temporal profiling of AU activation rather than a simple linear activation that current animation functions do

Is there currently a way of  Inputting temporal AU activation data rather than just a single activation
Ideally, the temporal AU activation data input would be a time series or a matrix, where rows represent time points and columns represent different AUs.

Many thanks

**Comment by ljchang** [comment]
Hi @hcuve, I'm not quite sure what you're asking. Are you asking about adding additional functionality to the plotting functions?  Or are you asking if we plan on training spatiotemporal AU models?

We've been refactoring our plotting tools and one of the options will be to slide through time. However, even without these new tools, you can always just plot the AU data over time.

While we are interested in spatiotemporal models, we currently don't have plans to train any in the near future. If you can find some existing ones, we can take a look and evaluate whether or not we can easily add it to the toolbox.

**Comment by ejolly** [comment]
@hcuve We don't currently support the functionality you're asking for, but you can roll your using matplotlib and the celluloid package for general figure animation. You can see an example of how we're doing this at the end of [this tutorial](https://py-feat.org/basic_tutorials/04_plotting.html#more-complex-animations).

You can skip calling the `interpolate_aus` function and simply loop over all your time points, call `plot_face` with the AUs for that time point, and them stitch them together into an animation using celluloid. Hope that helps!
