### ISSUE TITLE
The meaning of "skip_frames=24"

### ISSUE THREAD

**Issue by nuochen0818** [cosanlab/py-feat#204]
I am currently looking into the example code of "Detecting facial expressions from videos" and I got confused at this line of code: "video_prediction = detector.detect_video(test_video_path, skip_frames=24)", particularly the use of "skip_frames=24".

What does "skip_frames=24" signify? Is it because the example video has an actual frame rate of 24 frames per second (24Hz)?

**Comment by ejolly** [comment]
@nuochen0818 As we've noted in section 3.2 of the [detecting videos tutorial](https://py-feat.org/basic_tutorials/03_detector_vids.html), `skip_frames` tells the detector to only process every Nth frame, e.g. 24th frame. 

We do this in the tutorial for the interest of processing time, but you don't need to use it. Typically videos are 24, 30, 60, 120 or higher FPS and many frames will give the same exact detections. So this provides you extra control for how you want to handle so many frames.
