### ISSUE TITLE
ImportError: cannot import name 'binom_test' from 'scipy.stats' (Py-Feat 0.6.1, SciPy 1.12.0)

### ISSUE THREAD

**Issue by deepblue8581** [cosanlab/py-feat#205]
Hi,
I'm encountering an error when trying to import Py-Feat:

I'm using Pycharm and did a basic pip install py-feat  in terminal and everything looked fine until I tried to 'import feat'

Error: 
![binom error](https://github.com/cosanlab/py-feat/assets/62752966/83244a23-9174-40b4-8c1e-aea8a6f00f8f)

Environment:
Python version: 3.9.0
SciPy version: 1.12.0 
Py-Feat version: 0.6.1
Operating System: WIndows 10 

Thanks.

**Comment by wangruosi** [comment]
I encountered the same problem with Python 3.9. I created another environment using Python 3.8 and successfully ran a Jupyter Notebook demo. My environment:
Python=3.8.18
Scipy=1.10.1
Py-Feat=0.6.1
Operating System: Mac Intel

**Comment by deepblue8581** [comment]
Just Installed Python 3.8 and is now working, appreciated!
