### ISSUE TITLE
Move resources to new py-feat-data package and HuggingFace Hub

### ISSUE THREAD

**Issue by ejolly** [cosanlab/py-feat#221]
Currently we "check-point" models based on file-names and github releases. Moving forward we plan to move model weights into HuggingFace Hub and tie them to versioned released of a `py-feat-data` package.

@ejolly started local `lite` branch that has a dependency on a `py-feat-data` package. Can work off that, but should look into integrating with HuggingFace model-hosting and the tooling they have available:

https://huggingface.co/docs/hub/models-the-hub

**Comment by ljchang** [comment]
Starting discussion on this as I look into how to do this. The documentation is a little confusing, but it seems like all we need to do is add this [PyTorchModelHubMixIn](https://huggingface.co/docs/hub/en/models-uploading#upload-a-pytorch-model-using-huggingface_hub) class to our pytorch model classes, and then upload them to the hub to our py-feat organization and add a corresponding model card.

Then we will need to decide how to integrate the models into py-feat. Still figuring out the option space, but one is we just add a download from hub line when we initialize a detector class similar to how we do it to download the model checkpoints.  Another possibility is to more tightly integrate huggingface into py-feat and we could use the transformers library as an example of how they do it.

I'm starting with a single model to see how it all works and will report back.
