### ISSUE TITLE
Create a faster version of detection using pytorch computational graph

### ISSUE THREAD

**Issue by ljchang** [cosanlab/py-feat#229]
There are many reasons for the slow performance of py-feat issue #217 , #215 #182. One in particular is that we opted for a modular approach that allows us to flexibly combine many different models for several classes of feature extraction. For each feature extraction, we loop over each face detected within a frame and then loop over frames. We then sequentially proceed to the next feature extraction class.  This has led to slow performance because:
- we are duplicating processing steps multiple times such as processing images extracting faces etc.
- we are unable to take full advantage of GPUs because looping and switching to numpy breaks pytorch computational processing chain.
- we incur overhead to process issues arising from sequentially running different models (e.g., when face detection and pose detection find different numbers of faces).
- We are unable to process models as a computational graph

We are prototyping a new `FastDetector`, that has almost an identical API to our main `Detector` class, but instead attempts to pick sensible defaults that can be integrated into a pytorch computational graph, where many of these slow processes are streamlined.

This allows us to leverage a more scalable solution to host models on huggingface and easily incorporate new models that are also hosted on the huggingface_hub platform, which is the focus of issue #221 and #154 .

In addition, we hope this will address issues with GPUs #167 #203 and possibly MPS (though img2pose is the main holdup) #159, #187, #196.

We have also started adding support for torch.Tensors instead of just image filenames #225, #208, #168

**Comment by Gricardov** [comment]
Hi chamo!
When will those functionalities be available? Thanks in advance.

**Comment by Gricardov** [comment]
> There are many reasons for the slow performance of py-feat issue #217 , #215 #182. One in particular is that we opted for a modular approach that allows us to flexibly combine many different models for several classes of feature extraction. For each feature extraction, we loop over each face detected within a frame and then loop over frames. We then sequentially proceed to the next feature extraction class. This has led to slow performance because:
> 
> * we are duplicating processing steps multiple times such as processing images extracting faces etc.
> * we are unable to take full advantage of GPUs because looping and switching to numpy breaks pytorch computational processing chain.
> * we incur overhead to process issues arising from sequentially running different models (e.g., when face detection and pose detection find different numbers of faces).
> * We are unable to process models as a computational graph
> 
> We are prototyping a new `FastDetector`, that has almost an identical API to our main `Detector` class, but instead attempts to pick sensible defaults that can be integrated into a pytorch computational graph, where many of these slow processes are streamlined.
> 
> This allows us to leverage a more scalable solution to host models on huggingface and easily incorporate new models that are also hosted on the huggingface_hub platform, which is the focus of issue #221 and #154 .
> 
> In addition, we hope this will address issues with GPUs #167 #203 and possibly MPS (though img2pose is the main holdup) #159, #187, #196.
> 
> We have also started adding support for torch.Tensors instead of just image filenames #225, #208, #168

Hi chamo!
When will those functionalities be available? Thanks in advance.

**Comment by ljchang** [comment]
We are almost done with this refactor. I'm expecting it to be merged within the next couple of weeks.
