### ISSUE TITLE
Scrub the commit that uploaded a huge file

### ISSUE THREAD

**Issue by jcheong0428** [cosanlab/py-feat#74]

**Comment by TiankangXie** [comment]
This is very strange.. Yeah I tried so many times to delete it but failed. We should definitely meet and discuss about how to remove it completely

**Comment by ejolly** [comment]
We probably need to run something like https://rtyley.github.io/bfg-repo-cleaner/ to remove the files from git history in addition to the current commit. We were also committing a bunch of the jupyter book build files which we no longer need todo
