### ISSUE TITLE
Need more information about how to create a Fex object

### ISSUE THREAD

**Issue by ljchang** [cosanlab/py-feat#76]
should be in docstrings and tutorial.

1) we should be able to load a file
2) we should be able to convert a pandas/numpy etc

**Comment by jcheong0428** [comment]
Good point. I have sample notebooks which I can add to the Jupyter Book tutorial. 
Function themselves should already be in the [API docstrings](https://cosanlab.github.io/feat/api/index.html?highlight=read_feat#feat.data.Fex.read_feat) but obviously could be explained better.
