### ISSUE TITLE
Plot detections does not work with FACET and probably not OpenFace

### ISSUE THREAD

**Issue by jcheong0428** [cosanlab/py-feat#80]
KeyError: 'input'

-> 1532         inputs = self.input().unique()

FIX: make input column optional or change based on detector

**Comment by ljchang** [comment]
Given that nobody has access to FACET anymore, this is probably not an issue anymore.

We are keeping the dataloaders in `feat.utils.io` for now, but may remove them in the future to prevent code rot.
