### ISSUE TITLE
Pickling ("joblib") of sklearn model files shows warning when loaded with a different version of sklearn

### ISSUE THREAD

**Issue by jcheong0428** [cosanlab/py-feat#81]
We currently use joblib as recommended by sklearn  [https://scikit-learn.org/stable/modules/model_persistence.html](https://scikit-learn.org/stable/modules/model_persistence.html)
However this can cause issues when users have different sklearn version. See warnings below

`UserWarning: Trying to unpickle estimator PCA from version 0.24.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results.`

`Trying to unpickle estimator RandomForestClassifier from version 0.24.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.`

Not sure if we want to A) leave it as is, B) pin the sklearn version to where it was created, or C) explore other options - XML, PMML: [https://github.com/jpmml/sklearn2pmml](https://github.com/jpmml/sklearn2pmml)? 

Seems PMML could be good option?

**Comment by ejolly** [comment]
Partially addressed in #116 which tries to use `joblib` to load model if user versions match sklearn and Python the model was trained on. Leaving open in case we want to pursue a different solution or suppress warnings if we're rebuilding model instances from scratch using H5 files though.
