### ISSUE TITLE
evidence vs probabilities

### ISSUE THREAD

**Issue by jcheong0428** [cosanlab/py-feat#88]
evidence (log odds) is better suited to be used for analysis than probabilities which is bounded. we should provide functions to easily convert probabilities back and forth, or even consider using evidence entirely. 

We already have a softmax function, https://github.com/cosanlab/py-feat/blob/9ae6ef18b89989c95b3e85c26ed9f105c8a012c4/feat/utils.py#L542
and we should add the inverse (prob->evidence). 

And add it as a method to Fex, so that one can chain them. 
`fex.aus().evidence()`

**Comment by ljchang** [comment]
Let's revisit this in the future, once we finalize all of the detector modules.
