### ISSUE TITLE
Modify Interpolate method

### ISSUE THREAD

**Issue by ljchang** [cosanlab/py-feat#9]
At some point we should write a new interpolate method.  We can base it off of the upsample function.

It should:
1) be able to accomodate nonlinear methods such as cubic and spline.  Current one only seems to work with linear.
2) we should add a 'limit' flag which means it won't try to interpolate if chunk of time is too large.

**Comment by jcheong0428** [comment]
Aren't these already implemented on DataFrame.interpolate? 

See method and limit here:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.interpolate.html

**Comment by ljchang** [comment]
yeah, but everything except linear assumes the datetime format.  I would prefer if it works with our samples and sample_freq data representation without having to manually convert it.  

Didn't see the limit flag, that's nice.

**Comment by ljchang** [comment]
Also, interpolate does not seem to work if nans are missing at beginning of data.  We might need to find a method to just take the first value and backpropogate it to the beginning of the file in these cases.

**Comment by ljchang** [comment]
Not sure if interpolate should have this functionality, but sometimes it might be better to convert nans to zeros.

**Comment by ljchang** [comment]
I don't think that this is a high priority atm and the addition of multiple faces per frame makes this much more difficult to implement. Closing for now.
