### ISSUE TITLE
Add headpose detection

### ISSUE THREAD

**Issue by ichitaka** [cosanlab/py-feat#90]
While I can understand that there is no Gaze detection in this framework (as they are not really precise and need calibration), I really wished there would be a Headpose API. Are there any plans to integrate that in the future?

**Comment by jcheong0428** [comment]
@ichitaka Yes! We are actively working on this at the moment.

**Comment by ichitaka** [comment]
When do you expect to release this feature? Can I help somehow?

**Comment by kenneym** [comment]
Closed via #93. See https://py-feat.org/ for usage details and tutorials.
