### ISSUE TITLE
Exception Occurred when using Detector

### ISSUE THREAD

**Issue by sulibo** [cosanlab/py-feat#94]
An exception occurs when using "mobilenet" as the landmark model on my machine with CUDA installed. The other landmark models don't have this issue.
The exception seems to be caused by not all of the torch module's parameters and buffers are on GPU. 

```
Traceback (most recent call last):
  File "pyfeat_test.py", line 26, in <module>
    image_prediction = detector.detect_image(test_image)
  File "venv/lib/python3.8/site-packages/feat/detector.py", line 689, in detect_image
    df = self.process_frame(frame)
  File "venv/lib/python3.8/site-packages/feat/detector.py", line 540, in process_frame
    landmarks = self.detect_landmarks(
  File "venv/lib/python3.8/site-packages/feat/detector.py", line 366, in detect_landmarks
    landmark = self.landmark_detector(input).cpu().data.numpy()
  File "venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
```

Does anyone have an idea on how to solve this? Thanks!

**Comment by jcheong0428** [comment]
Thank you for raising this but I cannot seem to replicate the problem on my machine nor on Google Colab with GPU... If you can share a bit more of what machine/OS you are using, it might help us identify the issue. 
@TiankangXie: Any thoughts on why this might be the case? Can it be a venv~CUDA thing or do you think we missed something?

**Comment by sulibo** [comment]
@jcheong0428 Thanks for your response. Sure, see below. 

OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-53-generic x86_64) with CUDA 11.2
Machine: AMD Ryzen 5 and two GeForce RTX 2070 

I also tested it on Google Colab and another Ubuntu machine without CUDA (also in a virtual environment). There were no problems in both cases.

**Comment by jcheong0428** [comment]
@sulibo Thanks for the info. It potentially seems to be an issue related to having multiple GPUs which we haven't tested (although the exception message seems to suggest some params are on cpu). We will try to create a similar env with two GPUs and try to replicate the error and fix it in our next release if we can identify it. If not, we might have to rely on you to test a potential solution. [We found a similar issue raised elsewhere](https://github.com/huggingface/transformers/issues/1801) which might be the solution.

**Comment by sulibo** [comment]
> @sulibo Thanks for the info. It potentially seems to be an issue related to having multiple GPUs which we haven't tested (although the exception message seems to suggest some params are on cpu). We will try to create a similar env with two GPUs and try to replicate the error and fix it in our next release if we can identify it. If not, we might have to rely on you to test a potential solution. [We found a similar issue raised elsewhere](https://github.com/huggingface/transformers/issues/1801) which might be the solution.

@jcheong0428, thanks! I will check out the link, and just let me know if you will need me to test the new release.
